# Site configuration for Kelsey's Blog

exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

paginate: 5
paginate_path: blog/page:num

jekyll-mentions: https://twitter.com

author: Kelsey
social:
  name: Kelsey
  links:
    - https://github.com/你的GitHub用户名  # 可以改成你自己的GitHub链接

sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Asia/Shanghai

collections:
  posts:
    title: 博客
    output: true
    description: "Kelsey 的生活和记录"
    feature_text: |
      欢迎来到 Kelsey's Blog
    feature_image: "https://picsum.photos/2560/600?image=866"

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

encoding: utf-8
lang: zh-CN
title: "Kelsey's Blog"
logo: "/assets/logos/logo.svg"
description: "Kelsey 的个人博客，记录生活点滴和快乐"
url: "https://kelseychen.net"  # 改成你自己的GitHub Pages 地址
baseurl: ""
repo: "https://github.com/tomandpeter/kelseychen"
email: "lumber-lung-humble@duck.com"

css_inline: true

favicons:
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

navigation_header:
- title: 首页
  url: /
- title: 博客
  url: /blog/
- title: 分类
  url: /categories/
- title: 搜索
  url: /search/
- title: 留言板
  url: /message/

navigation_footer:
- title: 由 Kelsey 创作
  url: https://kelseychen.net

social_links:
  GitHub: https://kelseychen.net

disqus: "kelseychen"
  
# sharing_links:
#   Twitter: "#0d94e7"
#   facebook: "#3B5998"
#   Email: true

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
